<?php
/**
 * Invoice Template
 *
 * @author Austin Passy
 * 
 * Please do not edit this file, to create a custom invoice template:
 * 1. Copy the template folder to your current WordPress theme
 * 2. rename the folder to "wp-invoice"
 *
 **/
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>">
	<title><?php echo ucfirst( wp_invoice_get_type( get_the_ID() ) ); ?> #<?php echo wp_invoice_get_number( get_the_ID() ); ?> | <?php bloginfo( 'name' ); ?> &ndash; <?php the_title(); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="robots" content="noindex, nofollow">

    <link rel="stylesheet" href="<?php echo wp_invoice_get_template_url(); ?>/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="<?php echo wp_invoice_get_template_url(); ?>/style-print.css" type="text/css" media="print" />

<?php wp_head(); ?>
</head>
<body>

<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

<?php $user = wp_invoice_get_user( get_the_ID() ); //print_r( $user ); ?>

    <div class="container">
    
    	<div class="header">
        
        	<table cellpadding="0" cellspacing="0" align="left">
            	<tr>
                	<td>
                    <h3><?php echo apply_filters( 'wp_invoice_company_title', __( 'WP Invoice Pro', 'wp-invoice' ) ); ?></h3>
                            
                    <p><?php echo apply_filters( 'wp_invoice_company_subtitle', __( 'by Austin Passy', 'wp-invoice' ) ); ?></p>
                    
                    <p><a href="mailto:<?php echo apply_filters( 'wp_invoice_company_email', antispambot( get_the_author_meta('email'), 1 ) ); ?>"><?php echo apply_filters( 'wp_invoice_company_email', antispambot( get_the_author_meta('email') ) ); ?></a></p>
                    
                    <p><a href="<?php echo get_site_url(); ?>"><?php echo get_site_url(); ?></a></p>
                    </td>
                </tr>
            </table>
            
        </div><!-- .header -->
        
        <div class="info">
            <fieldset>
                <legend><?php _e( 'Sent to', 'wp-invoice' ); ?></legend>
                
                <p><strong><?php echo esc_attr( $user->data->display_name ); ?></strong></p>
                
                <?php $user_data = wp_invoice_get_user_meta( null, $user->data->ID ); ?>
                
                <p><big><?php echo esc_attr( $user_data['company'] ); ?></big></p>
                
                <?php $user_data['address_2'] = empty( $user_data['address_2'] ) ? $user_data['address_2'] : ' ' . esc_attr( $user_data['address_2'] ); ?>
                
                <?php $user_data['city'] = empty( $user_data['city'] ) ? $user_data['city'] : '<br>' . esc_attr( $user_data['city'] ); ?>
                
                <?php $user_data['state'] = empty( $user_data['state'] ) ? $user_data['state'] : ', ' . esc_attr( $user_data['state'] ); ?>
                
                <?php $user_data['postcode'] = empty( $user_data['postcode'] ) ? $user_data['postcode'] : ' ' . esc_attr( $user_data['postcode'] ); ?>
                
                <?php $user_data['country'] = empty( $user_data['country'] ) ? $user_data['country'] : '<br>' . esc_attr( $user_data['country'] ); ?>
                
                <address><?php echo $user_data['address_1'] . $user_data['address_2'] . $user_data['city'] . $user_data['state'] . $user_data['postcode'] . $user_data['country']; ?></address>
            </fieldset>
            
            <fieldset class="last">
                <legend><?php printf( __( '%s details', 'wp-invoice' ), ucfirst( wp_invoice_get_type( get_the_ID() ) ) ); ?></legend>
                
                <p><strong><?php _e( 'Project:', 'wp-invoice' ); ?></strong> <?php the_title(); ?></p>
                
                <p><?php printf( __( '<strong>%s number:</strong> %s', 'wp-invoice' ), ucfirst( wp_invoice_get_type( get_the_ID() ) ), esc_attr( wp_invoice_get_number( get_the_ID() ) ) ); ?></p>
                
                <p><strong><?php _e( 'Date Issued:', 'wp-invoice' ); ?></strong> <?php the_time( get_option('date_format') ); ?></p>
            </fieldset>            
            
        </div><!-- .info -->
                
		<?php if ( !empty( $post->post_content ) ) : ?>        
        <div class="hentry">
        
            <h3><?php _e( 'Notes:', 'wp-invoice' ); ?></h3>
            
            <?php the_content(); ?>
        
        </div><!-- .hentry -->
        <?php endif; ?>
        
        <div class="breakdown">
        
        	<table cellpadding="0" cellspacing="0">
                <tr class="heading">
                    <td><?php _e( 'Project Breakdown', 'wp-invoice' ); ?></td>
                    <td><?php _e( 'Type', 'wp-invoice' ); ?></td>
                    <td><?php _e( 'Rate', 'wp-invoice' ); ?></td>
                    <td><?php _e( 'Hours', 'wp-invoice' ); ?></td>
                    <td style="width:75px;"><?php _e( 'Subtotal', 'wp-invoice' ); ?></td>
                </tr>
                
                <?php global $wp_invoice_breakdown; ?>
                
                <?php while ( $wp_invoice_breakdown->have_fields_and_multi('detail') ) : ?>
                    <tr class="title">
                        <td><?php esc_attr( $wp_invoice_breakdown->the_value('title') ); ?></td>
                        <td><?php esc_attr( $wp_invoice_breakdown->the_value('type') ); ?></td>
                        <td><?php echo wp_invoice_currency_format( $wp_invoice_breakdown->get_the_value('rate') ); ?></td>
                        <td><?php esc_attr( $wp_invoice_breakdown->the_value('time') ); ?></td>
                        <td><?php echo wp_invoice_currency_format( $wp_invoice_breakdown->get_the_value('subtotal') ); ?></td>
                    </tr>
                    <tr class="description">
                        <?php $description = $wp_invoice_breakdown->get_the_value('description') != '' ? $wp_invoice_breakdown->get_the_value('description') : '&nbsp;'; ?>
                        <td><?php echo esc_html( $description ); ?></td>
                        <td colspan="4"></td>
                    </tr>                    
                <?php endwhile; ?>
                
                <?php global $wp_invoice_detail; ?>
                
                <?php $tax = $wp_invoice_detail->get_the_value('invoice_tax'); ?>
                
                <?php if ( !empty( $tax ) || ( intval( $tax ) <= (int)0 ) ) :  ?>
                <tr class="heading">
                    <td colspan="3"></td>
                    <td><?php _e( 'Subtotal', 'wp-invoice' ); ?></td>
                    <td><?php echo wp_invoice_currency_format( $wp_invoice_breakdown->get_the_value('subtotal') ); ?></td>
                </tr>
                <tr class="heading">
                    <td colspan="3"></td>
                    <td><?php _e( 'Tax', 'wp-invoice' ); ?></td>
                    <td><?php echo wp_invoice_currency_format( $wp_invoice_breakdown->get_the_value('tax') ); ?></td>
                </tr>
                <?php endif; ?>
                
                <tr class="heading">
                    <td colspan="3"></td>
                    <td class="total"><?php _e( 'Total', 'wp-invoice' ); ?></td>
                    <td class="total"><?php echo wp_invoice_currency_format( $wp_invoice_breakdown->get_the_value('total') ); ?></td>
                </tr>
            </table>
            
        </div><!-- .breakdown -->
        
        <div class="payment-details">
            <fieldset class="last">
            <legend><?php _e( 'Payment Details', 'wp-invoice' ); ?></legend>
            <?php if ( ucfirst( wp_invoice_get_type( get_the_ID() ) ) == __( 'Invoice', 'wp-invoice' ) ) : ?>
            
                <p><strong><?php _e( 'Bank:', 'wp-invoice' ); ?></strong> <span><?php echo apply_filters( 'wp_invoice_bank', 'Bank Name' ); ?></span></p>
                <p><strong><?php _e( 'Acc Name:', 'wp-invoice' ); ?></strong> <span><?php echo apply_filters( 'wp_invoice_account_name', 'My Account' ); ?></p>
                <p><strong><?php _e( 'Acc Routing:', 'wp-invoice' ); ?></strong> <span><?php echo apply_filters( 'wp_invoice_account_name', 'XXXXX-XXXXX-XXXXX' ); ?></p>
                <p><strong><?php _e( 'Acc Number:', 'wp-invoice' ); ?></strong> <span><?php echo apply_filters( 'wp_invoice_account_number', 'XXXXX-XXXX-XXXX' ); ?></span></p>
                
            <?php else: ?>
            
                <p><strong><?php _e( 'This is a project quote, not an invoice.', 'wp-invoice' ); ?></strong></p>
                <p><?php _e( 'No payment is required. Hope to hear from you soon.', 'wp-invoice' ); ?></p>
                
            <?php endif; ?>
            </fieldset>
        </div><!-- .payment-details -->
                
		<?php if ( ucfirst( wp_invoice_get_type( get_the_ID() ) ) == __( 'Invoice', 'wp-invoice' ) ) : ?>
            <p class="credits">
                <?php _e( '<strong>Important:</strong> The above invoice must be payed by Electronic Funds Transfer. Payment is due within 30 days from the date in this invoice. Late payment is subject to a fee of 5% per month.', 'wp-invoice' ); ?>
            </p>
        <?php endif; ?>        
        
    </div><!-- .container -->
    
    <?php comments_template( '/comments.php', true ); // Loads the comments.php template. ?>
    
<?php endwhile; endif; ?>

<?php wp_footer(); ?>

</body>
</html>