<?php
/**
 * Invoice Template
 *
 * @since 1.0.0
 * @alter 1.1.0
 * 
 * Please do not edit this file, to create a custom invoice template:
 * 1. Copy the template folder to your current wordpress theme
 * 2. rename the folder to "wp-invoice"
 *
 **/ 
if ( have_posts() ) : while ( have_posts() ) : the_post(); 
	
	global $payment_gateway_account;
	
	$payment_gateway_name		= wp_invoice_get_payment_gateway();
	$payment_gateway_name		= str_replace( ' ', '', $payment_gateway_name );
	
	$payment_gateway_account	= wp_invoice_get_payment_gateway_account();
	$payment_status 			= wp_invoice_get_invoice_status();
	$invoice_type 				= wp_invoice_get_invoice_type();
	
	if ( $payment_gateway_name != 'None' && ( $payment_gateway_account || $payment_gateway_name == 'Stripe' ) ) {
		$pay_ready = true;
	} else {
		$pay_ready = false;
	}

/**
 * Get the client ID and send it into our menu.
 * This creates the correct Dashboard link 
 *
 * We are also setting the wp_invoice_client_id Cookie
 *
 * @since 1.0
 **/
$terms = get_the_terms( $post->ID , 'client' );
$query_term = false;
if ( $terms )
{	
	$terms = array_values( $terms );
	$query_term = $terms[0]->term_id;		
}

if ( $query_term ) {
	$url 	= get_site_url();
	$url 	= parse_url( $url );
	$domain	= $url['host'];
	$path 	= isset( $url['path'] ) ? $url['path'] : '';
	
	if ( !isset( $_COOKIE['wp_invoice_client_id'] ) ) {
		wp_invoice_setcookie( 'wp_invoice_client_id', $query_term );
	} elseif ( $_COOKIE['wp_invoice_client_id'] != $query_term ) {
		wp_invoice_setcookie( 'wp_invoice_client_id', $query_term );
	}
}

// Display navigation menu
include_once( trailingslashit( WP_INVOICE_DIR ) . 'template/header.php' );

wp_invoice_get_menu( $query_term ); ?>
	
	<header>
		<section class="mini">
			<p><?php _e( 'Issued:', 'wp-invoice-pro' ); ?> <?php echo get_the_date(); ?></p>
			<h1><?php echo $invoice_type; ?></h1>
		</section>
		
		<section class="mini last">
			<p><?php _e( 'Unique ID:', 'wp-invoice-pro' ); ?></p>
			<h1>#<?php wp_invoice_number(); ?></h1>
		</section>
		
		<section class="controls">
			<div class="left-side">
				<a href="javascript:print()" class="print"><?php _e( 'Print', 'wp-invoice-pro' ); ?></a>
			</div>
			
		<?php if ( $pay_ready && $payment_status != 'Paid' && $invoice_type != 'Quote' ):
			
			include_once( trailingslashit( WP_INVOICE_DIR ) . 'functions/gateways/' . $payment_gateway_name . '.php' );
				
		elseif ( $payment_status == 'Paid' ) : ?>
			<div class="btn">
				<?php _e( 'Invoice Paid', 'wp-invoice-pro' ); ?>
			</div>
		<?php elseif ( $invoice_type == 'Quote' && wp_invoice_get_quote_approved() == __( 'Not yet', 'wp-invoice-pro' ) ) : ?>
			<a href="<?php echo add_query_arg( 'approved', 'yes', get_permalink( $post->ID ) ); ?>" class="btn"><?php _e( 'Approve', 'wp-invoice-pro' ); ?></a>
		<?php elseif ( wp_invoice_get_quote_approved() != __( 'Not yet', 'wp-invoice-pro' ) ):  ?>
			<div class="btn">
				<?php _e( 'Quote Approved', 'wp-invoice-pro' ); ?>
			</div>
		<?php endif; ?>
            
		</section>
	</header><!-- #invoice-header -->

	<?php if ( !$pay_ready && current_user_can( 'manage_options' ) ) : ?>
		<section class="alert">
			<p><strong><?php _e( 'Warning:', 'wp-invoice-pro' ); ?></strong> <?php _e( 'Payment account options have not been set. You will not receive payments until you set these, under Invoices &raquo; Options.', 'wp-invoice-pro' ); ?></p>
		</section>
	<?php endif; ?>
	
	<section id="to-from"<?php if ( $payment_status == 'Paid' ) echo ' class="paid-status"'; ?>>
			
		<div class="alignleft g4">
			<aside><?php _e( 'To:', 'wp-invoice-pro' ); ?></aside>
			<div class="info">
				<?php if ( wp_invoice_get_invoice_client_name() ) { ?>
                
                	<strong><?php wp_invoice_client(); ?></strong><br />
                    
				<?php } ?>
                
				<?php if ( wp_invoice_get_invoice_client_business() ) { ?>
                
					<?php wp_invoice_client_business(); ?><br />
                    
				<?php } ?>
                
				<?php if ( wp_invoice_get_invoice_client_business_address() ) { ?>
                
					<?php wp_invoice_client_business_address(); ?><br />
                    
				<?php } ?>
                
				<?php if ( wp_invoice_get_invoice_client_phone() ) { ?>
                
					<?php wp_invoice_client_phone(); ?><br />
                    
				<?php } ?>
                
				<?php if ( wp_invoice_get_invoice_client_email() ) { ?>
                
					<?php wp_invoice_client_email(); ?>
                    
				<?php } ?>
			</div><!-- # info -->
		</div><!-- # TO -->
		
		<div class="alignright g4 last">
			<aside><?php _e( 'From:', 'wp-invoice-pro' ); ?></aside>
			<div class="info">
				
				<?php
				$company = wp_invoice_get_option( 'company' );
				$address = wp_invoice_get_option( 'company_address' );
				$phone 	 = wp_invoice_get_option( 'company_phone' );
				?>
				
				<?php if ( $company ) { ?>
					<strong><?php echo $company; ?></strong><br><?php
				}
				if ( $address) {  ?>					
					<address><?php echo nl2br( $address ); ?></address><br><?php
				} if ( $phone ) { 					
					echo "$phone <br>";
				}
				wp_invoice_email(); ?>
			</div><!-- # info -->
		</div><!-- # FROM -->
		
	</section><!-- #to-from -->
	
	<?php if ( wp_invoice_has_details() ) : ?>
        <table class="invoice">
            <thead>
                <tr>
                    <th class="item"><?php _e( 'Item', 'wp-invoice-pro' ); ?></th>
                    <th class="type"><?php _e( 'Type', 'wp-invoice-pro' ); ?></th>
                    <th class="rate"><?php _e( 'Rate', 'wp-invoice-pro' ); ?></th>
                    <th class="quantity"><?php _e( 'Quantity', 'wp-invoice-pro' ); ?></th>
                    <th class="sub-total"><?php _e( 'Sub-total', 'wp-invoice-pro' ); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php while( wp_invoice_detail() ) : ?>
                <tr>
                    <td class="item"><?php wp_invoice_the_detail_title(); ?> <span class="description"><?php wp_invoice_the_detail_description(); ?></span></td>
                    <td><?php wp_invoice_the_detail_type(); ?></td>
                    <td><?php wp_invoice_the_detail_rate(); ?><?php if ( wp_invoice_get_the_detail_type() == 'Timed' ) _e( ' / hr', 'wp-invoice-pro' ); ?></td>
                    <td><?php wp_invoice_the_detail_duration(); ?></td>
                    <td><?php wp_invoice_the_detail_subtotal(); ?></td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
	<?php endif; ?>
	
	<?php if ( $post->post_content ) : ?>
		<div class="notes g7">
			<h2><?php _e( 'Notes:', 'wp-invoice-pro' ); ?></h2>
			<?php the_content(); ?>
		</div>
	<?php endif; ?>
	
	<div class="summary">
		<div class="row">
			<div class="title"><?php _e( 'Sub-total', 'wp-invoice-pro' ); ?></div>
			<div class="figure"><?php the_invoice_subtotal(); ?></div>
		</div>
		
		<div class="row">
			<div class="title"><?php _e( 'Tax', 'wp-invoice-pro' ); ?></div>
			<div class="figure"><?php the_invoice_tax(); ?></div>
		</div>
		
		<div class="row total">
			<div class="title"><?php _e( 'Amount Due', 'wp-invoice-pro' ); ?></div>
			<div class="figure"><?php the_invoice_total(); ?></div>
		</div>
		
		<?php if ( $pay_ready && $payment_status != 'Paid' && $invoice_type != 'Quote' ) :
		
			include_once( trailingslashit( WP_INVOICE_DIR ) . 'functions/gateways/' . $payment_gateway_name . '.php' );
			
		elseif ( $payment_status == 'Paid' ): ?>
        
			<div class="btn">
				<?php _e( 'Invoice Paid', 'wp-invoice-pro' ); ?>
			</div>
            
		<?php elseif ( $invoice_type == 'Quote' && wp_invoice_get_quote_approved() == __( 'Not yet', 'wp-invoice-pro' ) ): ?>
        
			<a href="<?php echo add_query_arg( 'approved', 'yes', get_permalink( $post->ID ) ); ?>" class="btn"><?php _e( 'Approve', 'wp-invoice-pro' ); ?></a>
            
		<?php elseif ( wp_invoice_get_quote_approved() != __( 'Not yet', 'wp-invoice-pro' ) ) : ?>
        
			<div class="btn">
				<?php _e( 'Quote Approved', 'wp-invoice-pro' ); ?>
			</div>
            
		<?php endif; ?>
        
	</div><!-- .summary -->
	
<?php endwhile; else: ?>
	
	<header>
		<section class="mini last">
			<p><?php _e( 'Not Found', 'wp-invoice-pro' ); ?></p>
			<h1>Invoice</h1>
		</section>
	</header><!-- #invoice-header -->
	
	<section class="page-entry">
		<h2><?php _e( 'Invoice Not Found', 'wp-invoice-pro' ); ?></h2>
		<p><?php _e( 'We\'re sorry, but that invoice doesn\'t seem to exist.', 'wp-invoice-pro' ); ?></p>
	</section>
	
<?php endif; ?>

<?php include_once( trailingslashit( WP_INVOICE_DIR ) . 'template/footer.php' ); ?>